/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package wuyun.cnl.trace;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2017-02-06")
public class Trace implements org.apache.thrift.TBase<Trace, Trace._Fields>, java.io.Serializable, Cloneable, Comparable<Trace> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Trace");

  private static final org.apache.thrift.protocol.TField TRACE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("traceID", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField CALL_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("callInfo", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TraceStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TraceTupleSchemeFactory());
  }

  public String traceID; // required
  public String callInfo; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TRACE_ID((short)1, "traceID"),
    CALL_INFO((short)2, "callInfo");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TRACE_ID
          return TRACE_ID;
        case 2: // CALL_INFO
          return CALL_INFO;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TRACE_ID, new org.apache.thrift.meta_data.FieldMetaData("traceID", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CALL_INFO, new org.apache.thrift.meta_data.FieldMetaData("callInfo", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Trace.class, metaDataMap);
  }

  public Trace() {
  }

  public Trace(
    String traceID,
    String callInfo)
  {
    this();
    this.traceID = traceID;
    this.callInfo = callInfo;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Trace(Trace other) {
    if (other.isSetTraceID()) {
      this.traceID = other.traceID;
    }
    if (other.isSetCallInfo()) {
      this.callInfo = other.callInfo;
    }
  }

  public Trace deepCopy() {
    return new Trace(this);
  }

  @Override
  public void clear() {
    this.traceID = null;
    this.callInfo = null;
  }

  public String getTraceID() {
    return this.traceID;
  }

  public Trace setTraceID(String traceID) {
    this.traceID = traceID;
    return this;
  }

  public void unsetTraceID() {
    this.traceID = null;
  }

  /** Returns true if field traceID is set (has been assigned a value) and false otherwise */
  public boolean isSetTraceID() {
    return this.traceID != null;
  }

  public void setTraceIDIsSet(boolean value) {
    if (!value) {
      this.traceID = null;
    }
  }

  public String getCallInfo() {
    return this.callInfo;
  }

  public Trace setCallInfo(String callInfo) {
    this.callInfo = callInfo;
    return this;
  }

  public void unsetCallInfo() {
    this.callInfo = null;
  }

  /** Returns true if field callInfo is set (has been assigned a value) and false otherwise */
  public boolean isSetCallInfo() {
    return this.callInfo != null;
  }

  public void setCallInfoIsSet(boolean value) {
    if (!value) {
      this.callInfo = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TRACE_ID:
      if (value == null) {
        unsetTraceID();
      } else {
        setTraceID((String)value);
      }
      break;

    case CALL_INFO:
      if (value == null) {
        unsetCallInfo();
      } else {
        setCallInfo((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TRACE_ID:
      return getTraceID();

    case CALL_INFO:
      return getCallInfo();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TRACE_ID:
      return isSetTraceID();
    case CALL_INFO:
      return isSetCallInfo();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Trace)
      return this.equals((Trace)that);
    return false;
  }

  public boolean equals(Trace that) {
    if (that == null)
      return false;

    boolean this_present_traceID = true && this.isSetTraceID();
    boolean that_present_traceID = true && that.isSetTraceID();
    if (this_present_traceID || that_present_traceID) {
      if (!(this_present_traceID && that_present_traceID))
        return false;
      if (!this.traceID.equals(that.traceID))
        return false;
    }

    boolean this_present_callInfo = true && this.isSetCallInfo();
    boolean that_present_callInfo = true && that.isSetCallInfo();
    if (this_present_callInfo || that_present_callInfo) {
      if (!(this_present_callInfo && that_present_callInfo))
        return false;
      if (!this.callInfo.equals(that.callInfo))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_traceID = true && (isSetTraceID());
    list.add(present_traceID);
    if (present_traceID)
      list.add(traceID);

    boolean present_callInfo = true && (isSetCallInfo());
    list.add(present_callInfo);
    if (present_callInfo)
      list.add(callInfo);

    return list.hashCode();
  }

  @Override
  public int compareTo(Trace other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetTraceID()).compareTo(other.isSetTraceID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTraceID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.traceID, other.traceID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCallInfo()).compareTo(other.isSetCallInfo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCallInfo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.callInfo, other.callInfo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Trace(");
    boolean first = true;

    sb.append("traceID:");
    if (this.traceID == null) {
      sb.append("null");
    } else {
      sb.append(this.traceID);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("callInfo:");
    if (this.callInfo == null) {
      sb.append("null");
    } else {
      sb.append(this.callInfo);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TraceStandardSchemeFactory implements SchemeFactory {
    public TraceStandardScheme getScheme() {
      return new TraceStandardScheme();
    }
  }

  private static class TraceStandardScheme extends StandardScheme<Trace> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Trace struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TRACE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.traceID = iprot.readString();
              struct.setTraceIDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CALL_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.callInfo = iprot.readString();
              struct.setCallInfoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Trace struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.traceID != null) {
        oprot.writeFieldBegin(TRACE_ID_FIELD_DESC);
        oprot.writeString(struct.traceID);
        oprot.writeFieldEnd();
      }
      if (struct.callInfo != null) {
        oprot.writeFieldBegin(CALL_INFO_FIELD_DESC);
        oprot.writeString(struct.callInfo);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TraceTupleSchemeFactory implements SchemeFactory {
    public TraceTupleScheme getScheme() {
      return new TraceTupleScheme();
    }
  }

  private static class TraceTupleScheme extends TupleScheme<Trace> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Trace struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetTraceID()) {
        optionals.set(0);
      }
      if (struct.isSetCallInfo()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetTraceID()) {
        oprot.writeString(struct.traceID);
      }
      if (struct.isSetCallInfo()) {
        oprot.writeString(struct.callInfo);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Trace struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.traceID = iprot.readString();
        struct.setTraceIDIsSet(true);
      }
      if (incoming.get(1)) {
        struct.callInfo = iprot.readString();
        struct.setCallInfoIsSet(true);
      }
    }
  }

}

